# Generated by Django 4.2.30 on 2026-05-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_place_status_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='best_season',
            field=models.CharField(blank=True, choices=[('Monsoon', 'Monsoon (June–August)'), ('Winter', 'Winter (November–February)'), ('Summer', 'Summer (March–May)'), ('Year Round', 'Year Round')], max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Incorrect Information', 'Incorrect Information'), ('Inappropriate Content', 'Inappropriate Content'), ('Spam or Fake', 'Spam or Fake'), ('Offensive Images', 'Offensive Images'), ('Place Does Not Exist', 'Place Does Not Exist'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.place')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('place', 'reported_by')},
            },
        ),
    ]
