# Generated by Django 4.2.30 on 2026-05-25 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0003_place_best_season_place_share_count_placeimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_type', models.CharField(choices=[('Safety', 'Safety'), ('Transport', 'Transport'), ('Food and Water', 'Food and Water'), ('Best Time', 'Best Time'), ('What to Carry', 'What to Carry'), ('Permits Required', 'Permits Required'), ('Wildlife Warning', 'Wildlife Warning'), ('General', 'General')], max_length=30)),
                ('content', models.TextField(max_length=500)),
                ('helpful_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_tips', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_tips', to='places.place')),
            ],
            options={
                'ordering': ['-helpful_count', '-created_at'],
            },
        ),
    ]
